name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Enhancement'
    label: 'enhancement'
  - title: 'ğŸ› Fixes'
    label: 'bug'
  - title: 'ğŸ¿ ETC'
    label: 'etc'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  # What's Changed
  $CHANGES